<?php

/**
 * @file
 * This is Media: 23 Video's installation, configuration, and removal file.
 */

/**
 * Implementation of hook_uninstall().
 */
function media_23video_uninstall() {
  foreach (media_23video_variable_default() as $variable => $value) {
    media_23video_variable_del($variable);
  }
  return array(array('success' => TRUE, 'query' => "Deleted all variables in the Media: 23 Video namespace."));
}
